# Workflow pour déployer automatiquement sur GitHub Pages
name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ] # Déclenche sur push vers main
  pull_request:
    branches: [ main ]

# Permissions nécessaires pour GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Un seul déploiement à la fois
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Job de build
  build:
    runs-on: ubuntu-latest
    container: node:22.12.0
    env:
      # Option B (partie 1): on charge d'abord les Secrets dans l'environnement
      VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
      VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fallback to Repository Variables if secrets missing
        run: |
          if [ -z "${VITE_SUPABASE_URL}" ] && [ -n "${{ vars.VITE_SUPABASE_URL }}" ]; then
            echo "VITE_SUPABASE_URL=${{ vars.VITE_SUPABASE_URL }}" >> $GITHUB_ENV
          fi
          if [ -z "${VITE_SUPABASE_ANON_KEY}" ] && [ -n "${{ vars.VITE_SUPABASE_ANON_KEY }}" ]; then
            echo "VITE_SUPABASE_ANON_KEY=${{ vars.VITE_SUPABASE_ANON_KEY }}" >> $GITHUB_ENV
          fi

      - name: Check Supabase env
        run: |
          if [ -z "${VITE_SUPABASE_URL}" ] || [ -z "${VITE_SUPABASE_ANON_KEY}" ]; then
            echo "AVERTISSEMENT: VITE_SUPABASE_URL ou VITE_SUPABASE_ANON_KEY manquant(s). L'app utilisera le fallback local."
          else
            echo "Variables VITE_SUPABASE_* présentes."
          fi

      - name: Install dependencies (clean)
        run: |
          npm ci

      - name: Build
        run: |
          echo "Node version during build:" && node -v
          echo "NPM version during build:" && npm -v
          npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  # Job de déploiement
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4